name: CI
on:
  push:
    branches: main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  test:
    if: github.event_name == 'push'
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test --all-features --workspace
    timeout-minutes: 10
