name: CI
env:
  RUSTFLAGS: -AWarnings
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main
permissions:
  contents: read
jobs:
  stable:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run Cargo Test
      run: cargo test --all-features --workspace
  nightly:
    name: Nightly
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Run Cargo Test
      run: cargo nightly fmt --all-features --workspace -- check
    - name: Run Cargo Test
      run: 'cargo nightly clippy --all-features --workspace -- -D warnings '
