name: CI
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main
permissions:
  contents: read
jobs:
  stable:
    name: Rust Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run Cargo Test
      run: RUSTFLAGS="-Awarnings" cargo test --all-features --workspace
  nightly:
    name: Rust Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Check Formatting
      run: cargo fmt -- --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings
